require('dotenv').config();
require('./config/database');

const Category = require('./models/category');
const Item = require('./models/item');

(async function() {

  await Category.deleteMany({});
  const categories = await Category.create([
    {name: 'Apperal / Accessories', sortOrder: 10},
    {name: 'Brakes', sortOrder: 20},
    {name: 'Cooling', sortOrder: 30},
    {name: 'Drivetrain', sortOrder: 40},
    {name: 'Engine', sortOrder: 50},
    {name: 'Exhaust', sortOrder: 60},
    {name: 'Exterior', sortOrder: 70},
    {name: 'Suspension', sortOrder: 80},
    {name: 'Wheels & Accessories', sortOrder: 90},
  ]);

  await Item.deleteMany({});
  const items = await Item.create([
    {name: 'Hunts & Co. Tee',brand:'Hunts & Co.', description: "Hit the road! You'll be ready for your next adventure in this tee.",sku:'HAC-TEE-100', url: 'https://i.imgur.com/D3HooHA.jpg', category: categories[0], price: 25.95},
    {name: 'Overdue Skull Hoodie',brand:'Overdue', description: "Be the envy of all the enthusiasts and proudly sport this Overdue Skull Hoodie. A great addition to any enthusiast's wardrobe.",sku:'OVR-SKH-100', url: 'https://i.imgur.com/rIoQWZv.jpg', category: categories[0], price: 55.95},
    {name: 'Anti Grip Grip Club Hoodie',brand:'Anti-Club', description: "Our Candy Red Mid weight Hooded Pullover has individual and unique character we accomplish during our full garment dying process. Made with ultra soft cotton/polyester blend fleece in an amazing red color, this garment is as comfortable as they are eye catching.",sku:'ANT-TEE-100', url: 'https://i.imgur.com/AM2tBm5.jpg', category: categories[0], price: 65.95},
    {name: 'JDM Tee',brand:'JDM', description: "Hit the road! You'll be ready for your next adventure in this tee.",sku:'JDM-TEE-100', url: 'https://i.imgur.com/dYYa25s.jpg', category: categories[0], price: 25.95},
    {name: 'Cross Arrow Tee',brand:'Cross Arrow', description: "Hit the road! You'll be ready for your next adventure in this tee.",sku:'CRA-TEE-100', url: 'https://i.imgur.com/R2zWKcl.jpg', category: categories[0], price: 25.95},
    {name: 'BREMBO FRONT 4 PISTON SLOTTED OR DRILLED BRAKE KIT', brand:'Brembo', description:'This brake package increases your overall breaking performance and are OE quality. If your 86 spends long times on the roads and occasional periods on the track, this is a great solution. SOLD AS A PAIR', sku:'BRM-BRK-201', url:'https://i.imgur.com/MKuTKGH.jpg', category: categories[1], price: 1915.95},
    {name: 'Stoptech Sport Kit Drilled Front Kit', brand:'StopTech', description:"The StopTech Sport Kit is an excellent choice for the enthusiast whose rotors are nearing the end of their service life. StopTech's Sport Kit includes direct replacement OE diameter rotors, performance brake pads, and stainless steel brake lines. Stainless steel lines provide immediate response to brake pedal input and give better feedback. Performance brake pads offer improved stopping power in all conditions with less dust than other pads. Quality is assured as all components are manufactured to meet or exceed all OE specifications.", sku:'STT-DFK-201', url:'https://i.imgur.com/E86EEaE.jpg', category: categories[1], price: 566.95},
    {name: 'MTEC Stainless Steel Brake Lines', brand: 'MTEC', description:'MTEC Industries brake lines are made of the finest PTFE hose with a stainless steel wire braided cover and permanently crimped-on zinc plated steel fittings. They reduce volumetric expansion giving you the reliability and safety you demand. Stainless steel lines will give protection from issues along with enhancing the appearance of your installation. Overtime and under continuous use OEM rubber lines can swell and expand, exposing the driver to brake fade. The rubber cover is also vulnerable to attacks from the ozone layer rubber which causes it to deteriorate. Rubber hoses might be susceptible to flying debris in extreme applications such as auto crossing, hard driving, and racing.', sku: 'MTC-BKL-201', url: 'https://i.imgur.com/PCwXJWx.jpg', category: categories[1], price: 120.95},
    {name: 'Carbotech Street Pad Sprint Kit', brand: 'Carbotech', description:'Carbotech is the first in this specific racing compounds. It has better initial bite at race temperatures, higher coefficient of friction, excellent modulation and release characteristics.', sku: 'CBT-BKP-201', url: 'https://i.imgur.com/f118rON.jpg', category: categories[1], price: 189.99},
    {name: 'Brake Fluid DOT 4 1L', brand: 'ATE', description:'This is a DOT4 brake fluid that can be used for race, as well as street use. This is a long lasting fluid that can remain in use for at least 3 years. But its also compatible with most DOT3, DOT4, or DOT5.1 fluids.', sku: 'ATE-BKF-201', url: 'https://i.imgur.com/Fe6mST8.png', category: categories[1], price: 15.99},
    {name: 'P.MU BRAKE FLUID CAP COVER', brand: 'Project Mu Co.', description: "This brake fluid cap cover is made of aluminum and features the P.MU logo on top. It installs in seconds by slipping over the factory piece. There's a set screw on the side to tighten it down. Anodized finish.", sku: 'T86-BKC-201', url: 'https://i.imgur.com/aUuftPp.jpg', category: categories[1], price: 43.95},
    {name: 'KOYO ALUMINUM RACING RADIATOR', brand: 'KOYO', description:'Koyo radiators have exceptional quality and are a great replacement for OEM radiators. They are designed to be a plug and play replacement that delivers more performance than your factory radiator.', sku: 'KYO-RAD-302', url: 'https://i.imgur.com/qrMV35k.jpg', category: categories[2], price: 387.95},
    {name: 'MISHIMOTO PERFORMANCE RADIATOR', brand: 'MISHIMOTO', description:'The Scion FR-S / Subaru BRZ is the perfect car for tearing up back roads or hitting the autocross course. Aggressive driving results in increased engine temperatures necessitating an effective solution for keeping your flat four cool. Mishimoto has the perfect upgrade, the Scion FR-S / Subaru BRZ performance aluminum radiator, to eliminate rising temperatures.', sku: 'MIS-RAD-302', url: 'https://i.imgur.com/kFefjVI.png', category: categories[2], price: 401.96},
    {name: 'MISHIMOTO Silicone Radiator Hose Kit', brand: 'MISHIMOTO', description:'Mishimoto Silicone Radiator Hose Kit for the Scion FRS/Subaru BRZ 13+. Mishimoto silicone radiator hose kits and silicone couplers will provide your engine with a one-of-a-kind advantage in performance and style', sku: 'MIS-SRH-302', url: 'https://i.imgur.com/onbpcv0.jpg', category: categories[2], price: 121.96},
    {name: 'CSF Aluminum Racing Radiator', brand: 'CSF', description:'CSF manufactures the most advanced and efficient radiator cores in the industry by using innovative tube and fin technologies with industry leading testing methods to maximize airflow and heat dissipation. ', sku: 'CSF-ARR-302', url: 'https://i.imgur.com/9jFuysN.jpg', category: categories[2], price: 321.96},
    {name: 'ACT HEAVY DUTY SOLID 6-PUCK DISC CLUTCH KIT', brand: 'ACT', description:'ACT Heavy Duty pressure plates use exclusive diaphragm design to increase clamp load, reduce deflection and maximize clutch life. All diaphragms endure a four-stage, heat-treating process for unparalleled performance.Torque capacity rated at 345 ft/lbs', sku: 'ACT-CLT-403', url: 'https://i.imgur.com/D4iDzmF.jpg', category: categories[3], price: 650.99},
    {name: 'XCLUTCH FlyWheel', brand: 'XCLUTCH', description:'Direct Fitment SFI Apprroved - Works well with OEM clutch Kits.', sku: 'XCL-FLY-403', url: 'https://i.imgur.com/zKojt0w.jpg', category: categories[3], price: 259.94},
    {name: 'STI JDM SHORT SHIFTER (6MT)', brand: 'OEM', description:'The Subaru BRZ shifter is loose for many drivers. It can be easily improved with this STi Short Shifter Assembly from Japan. This assembly gives your shifting a more precise and solid feel.', sku: 'STI-OSS-403', url: 'https://i.imgur.com/C8TGUhW.jpg', category: categories[3], price: 549.95},
    {name: 'OS GIKEN SUPER LOCK LIMITED SLIP DIFFERENTIAL', brand: 'OS GIKEN', description:"OS Giken's testing has found the FT-86 chassis to perform much faster utilizing their custom spec 1- Way differential tuning. Typically Torsen differentials do not evenly distribute applied power and never achieve 100% lock. The OS Giken Super Lock allows for precise lock timing for consistency in performance regardless of surface conditions.", sku: 'OSG-LSD-403', url: 'https://i.imgur.com/jytJAdj.jpg', category: categories[3], price: 1450.99},
    {name: 'TRD QUICK SHIFT KIT', brand: 'TRD', description:"TRD Quick Shift Kit for the Scion FRS or Subaru BRZ is a cheap and easy way to get into the next gear easier and of course faster. Design of quickshifter optimizes linkage and location to shorten shift throw up to 25%, providing the vehicle with a race-car-like feel, without compromising quality, fit and finish.", sku: 'TRD-QSK-403', url: 'https://i.imgur.com/iGlnxoI.jpg', category: categories[3], price: 250.99},
    {name: 'WORKS OIL REGULATOR KIT' , brand: 'WORKS', description:"This ultimate 86 engine oil temperature regulator serves two important functions, while using OEM components! This kit minimizes the oil temperature and pressure issues prone the the 86 chassis.", sku: 'WRK-ORK-504', url: 'https://i.imgur.com/LLU11Dc.jpg', category: categories[4], price: 339.99},
    {name: 'STI SPORTS PERFORMANCE OIL FILTER', brand: 'STI', description:"This oil filter is used by many service technicians during routine oil changes. It is the model listed in Subaru's system for the 2015-2020 Subaru WRX / 2013-2020 FRS / BRZ / 86 .", sku: 'STI-POF-504', url: 'https://i.imgur.com/x8u79g7.jpg', category: categories[4], price: 48.99},
    {name: 'GRAMS PERFORMANCE 550CC INJECTOR KIT', brand: 'GRAMS PERFORMANCE', description:"The fuel system of your powerful 2013-2020 FR-S, BRZ, and 86 can handle some big power numbers without needing an upgrade, but when you start talking about massive supercharger head units, or even better, upgrades for those head units, you're going to need some high-powered and reliable fuel injectors to keep your FR-S, BRZ, and 86 from getting thirsty.", sku: 'GRP-IJK-504', url: 'https://i.imgur.com/oywA3r7.jpg', category: categories[4], price: 334.99},
    {name: 'HKS GT2 SUPERCHARGER SYSTEM PRO', brand: 'HKS', description:'The FR sports car "86 & BRZ" was born in the heyday of eco-cars. HKS has released various tuning parts from the beginning. The main body of one of them, the supercharger kit, has been renewed to GT2.', sku: 'HKS-SCK-504', url: 'https://i.imgur.com/z3SiCxH.jpg', category: categories[4], price: 3800.00},
    {name: 'IGNITION PROJECTS QUAD SPARK IGNITION COIL PACKS', brand: 'IGNITION PROJECTS', description:'With constant research and development, we were be able to build the Quad-spark system directly into the ignition coil without using an external discharge box. Our Quad-spark technology creates a secondary voltage and produces a 46% increase in secondary current.', sku: 'IGP-ICP-504', url: 'https://i.imgur.com/uWXnPXz.jpg', category: categories[4], price: 442.99},
    {name: 'GRIMMSPEED HEAD GASKET SET (FA20)', brand: 'GRIMMSPEED', description:"GrimmSpeed has set the standard for quality when it comes to aftermarket replacement gaskets so it’s only natural that they should offer our fans the MOST important gaskets their car will ever need: Introducing The GrimmSpeed FA20 Head Gasket Sets!", sku: 'GRM-HDG-504', url: 'https://i.imgur.com/2UdMMhH.jpg', category: categories[4], price: 169.99},
    {name: 'ECUTEK FT86 BOOST TUNE', brand: 'ECUTEK', description:'This flash develops an increase in TQ and HP throughout the entire power band and is required whenever you add boost to your car. It will work for Vortech, Innovate, HKS, Greddy, and more.', sku: 'ECT-BTU-504', url: 'https://i.imgur.com/S9ap1ab.jpg', category: categories[4], price: 350.00},
    {name: 'HKS BOLT-ON TURBO KIT', brand: 'HKS', description:'The combination of the best designed impellor and optimum housing can be felt when installed to the car. A wide efficiency range means matching the turbo to engine is now easier. Reduced surging offers more freedom to select optimum boost levels. GTIII turbos use lightweight impellors with optimised wastegate port design and valve sizing, actuator spring rate is selected to each vehicle spec for optimum response.', sku: 'HKS-BTK-504', url: 'https://i.imgur.com/uFSORrY.jpg', category: categories[4], price: 4800.00},
    {name: 'GREDDY 6 PIECE ALUMINUM ENGINE PULLEY KIT', brand: 'GREEDY', description:'Full 6 piece Aluminum engine pulley kit Increases engine response.', sku: 'GRD-AEP-504', url: 'https://i.imgur.com/4USRt5W.jpg', category: categories[4], price: 741.99},
    {name: 'EDELBROCK SUPERCHARGER SYSTEM (NO TUNING)', brand: 'EDELBROCK', description:'The Edelbrock system is capable of achieving great gains with the Scion FR-S / Subaru BRZ. This thing weighs 120lbs for delivery so choose your option below carefully. No Lift Gate means you are going to get a work out or need a buddy to help you.', sku: 'EDB-SCK-504', url: 'https://i.imgur.com/APxxKXD.jpg', category: categories[4], price: 4750.97},
    {name: 'MEGAN RACING CAT-BACK SYSTEM DRIFT SPEC STAINLESS STEEL TIP', brand: 'MEGAN RACING', description:'One of Megan Racing s strongest products, the Cat-Back System is made of SUS-304 Stainless Steel with a fully polished surface, CNC machined flanges and mandrel bends. Its aggressive styling, and deep, strong tone are just part of the MR Cat-Back characteristics.', sku: 'MGN-CBS-605', url: 'https://i.imgur.com/IuZGC1x.jpg', category: categories[5], price: 451.99},
    {name: 'PLM POWER DRIVEN TRACKPIPE MUFFLER DELETE WITH DUAL TIPS', brand: 'PLM', description:'Private label MFG Track-pipes are made of 304 TIG welded stainless steel and weighs at a remarkable 13 lbs. Compared to the stock brick of a muffler that weighs 26 pounds and you save 13 pounds. The piping of this Track-pipe is an OD (OUT DIAMETER) of 2.5/65mm Dual Exit for the most direct exhaust path Quick 15 minute install using only hand tools.', sku: 'PLM-MDP-605', url: 'https://i.imgur.com/AQBBmQY.jpg', category: categories[5], price: 532.99},
    {name: 'TOYOTA O2 SENSOR', brand: 'OEM', description:"This is a direct OEM Toyota replacement 02 Sensor. Can't go wrong with OEM!", sku: 'OEM-OSN-605', url: 'https://i.imgur.com/ZIsz6IW.jpg', category: categories[5], price: 122.45},
    {name: 'PRIVATE LABEL MFG MUFFLER DELETE V2 TRACK PIPE', brand: 'PRIVATE LABEL MFG', description:'Private label MFG Track-pipes are made of TIG welded stainless steel and weighs at a remarkable 3 lbs. Compared to the stock brick of a muffler that weighs 26 pounds and you save 23 pounds. The piping of this Track-pipe is an OD (OUT DIAMETER) of 2.5/65mm Single Exit on the drivers side for the most direct exhaust path Quick 15 minute install using only hand tools Ultra light weight of 3lbs.', sku: 'PVT-MDP-605', url: 'https://i.imgur.com/8h7KLOO.jpg', category: categories[5], price: 219.99},
    {name: 'FT-86 SPEEDFACTORY V1 CAT BACK EXHAUST (RESONATED)', brand: 'FT-86', description:" A V-Band clamp was used to attach the axle back portion for ease of install, and future V2 (right side single exit) and V3 (no muffler single exit) upgrade options. You hear the exhaust when you want to, by letting the RPM's wrap out with your foot firmly on the floor, and don't hear it when cruising at 3000 RPM down the highway.", sku: 'FTS-CAT-605', url: 'https://i.imgur.com/8BYLTmZ.jpg', category: categories[5], price: 989.99},
    {name: 'HKS LEGAMAX SPORTS QUAD TIP EXHAUST SYSTEM', brand: 'HKS', description:'HKS Scion FRS and Subaru BRZ Legamax Sports Muffler cat back exhaust. This unique and simple exhaust system will set you apart from the rest.', sku: 'HKS-QTE-605', url: 'https://i.imgur.com/u0tiBvO.jpg', category: categories[5], price: 1129.99},
    {name: 'VALENTI JEWEL LED TAIL LIGHT CLEAR LENS WITH RED CHROME INNER HOUSING', brand: 'VALENTI', description:'The transition from stock tail lights to Valenti Jewel LED Tail Lights will transform the look of your vehicle.', sku: 'VAL-JTL-706', url: 'https://i.imgur.com/JoY87ID.jpg', category: categories[6], price: 573.49},
    {name: 'OLM CS2 STYLE CARBON FIBER FRONT LIP', brand: 'OLM', description:'From front to back OLM CS style body parts will enhance the look of your 2017+ BRZ.', sku: 'OLM-LIP-706', url: 'https://i.imgur.com/Lo6i9sX.jpg', category: categories[6], price: 389.97},
    {name: 'OLM CARBON WRAP REAR WINDOW ROOF VISOR / SPOILER', brand: 'OLM', description:'Change the appearance of your vehicle with this stylish OLM Rear Window Spoiler.', sku: 'OLM-RWV-706', url: 'https://i.imgur.com/sJwAEgI.jpg', category: categories[6], price: 129.98},
    {name: 'SEIBON CARBON FIBER SPOILER (GD)', brand: 'SEIBON', description:'Seibon Carbon components are carefully hand-crafted using only the finest materials. Our production team offers superior craftsmanship with over 15 years of experience working with carbon fiber.', sku: 'SEI-CFS-GD_706', url: 'https://i.imgur.com/VH82bIA.jpg', category: categories[6], price: 923.89},
    {name: 'SEIBON CARBON FIBER SPOILER (AG)', brand: 'SEIBON', description:'Seibon Carbon components are carefully hand-crafted using only the finest materials. Our production team offers superior craftsmanship with over 15 years of experience working with carbon fiber.', sku: 'SEI-CFS-AG-706', url: 'https://i.imgur.com/2qikGJu.jpg', category: categories[6], price: 832.34},
    {name: 'SUBARU OEM STI SIDE SKIRTS', brand: 'STI', description:'Continue the mean ground-hugging attitude down the rocker panels of the WRX or STI. Kit includes both left and right side under spoilers. Includes STI logo.', sku: 'STI-OSS-706', url: 'https://i.imgur.com/6OwzLUw.gif', category: categories[6], price: 499.99},
    {name: 'APR GTC-200 CARBON FIBER WING', brand: 'APR', description:'Spanning 60.5 inches and a height of 10 inches, the New GTC-200 adjustable wing for the Scion FR-S and Subaru BRZ offers the perfect amount of downforce for midsize and compact cars. Computational Fluid Dynamics (CFD) analysis was performed on this wing to support validation of its aerodynamic design.', sku: 'APR-CFW-706', url: 'https://i.imgur.com/jI0tZSh.jpg', category: categories[6], price: 932.53},
    {name: 'SEIBON CARBON FIBER SPOILER (GT)', brand: 'SEIBON', description:'Seibon Carbon components are carefully hand-crafted using only the finest materials. Our production team offers superior craftsmanship with over 15 years of experience working with carbon fiber.', sku: 'SEI-CFG-706', url: 'https://i.imgur.com/1w3CzuL.jpg', category: categories[6], price: 1294.93},
    {name: 'TEIN STREET ADVANCE Z COILOVERS', brand: 'TEIN', description:"The Tein Street Advance Z Coilovers which are a great cost-effective set of coilovers that won't break the bank.", sku: 'TEI-LWS-807', url: 'https://i.imgur.com/jusVQlh.jpg', category: categories[7], price: 732.92},
    {name: 'ST SUSPENSION XA COILOVER KIT', brand: 'ST SUSPENSIONS', description:'For drivers wanting more than just ride height adjustment comes the ST XA coilover. Developed alongside KW Automotive the ST XA allows individual adjustment of the damping to suit just about all your driving needs!', sku: 'STS-CIL-807', url: 'https://i.imgur.com/sppGyj9.jpg', category: categories[7], price: 989.00},
    {name: 'AIR LIFT PERFORMANCE 3P AIR SUSPENSION CONTROL UNIT W/ COMPRESSOR AND TANK', brand: 'AIRLIFT', description:'Air Lift Performance 3P combines pressure-based control with the ability to add ride-height sensing technology with the upgrade to height sensors. While both types of air management have been utilized before, this is the first product to harness the benefits of both sytems – instantly improving suspension control, performance, and vehicle ride flexibility.', sku: 'AIR-ASC-807', url: 'https://i.imgur.com/WXBRTmf.jpg', category: categories[7], price: 1674.98},
    {name: 'SILVERS NEOMAX SERIES COILOVER', brand: "SILVER'S", description:"Backed by racing experience and motivated by a desire to help enthusiasts achieve their goals, Silver's has released with NeoMax series for the 13+ FR-S / BRZ / 86 platform.", sku: 'SLV-NSC-807', url: 'https://i.imgur.com/5RCiAVz.png', category: categories[7], price: 1198.93},
    {name: 'CUSCO HOLLOW SWAY BAR (REAR, 16MM)', brand: 'CUSCO', description:'CUSCO 16mm hollow rear sway bar for the Scion FR-S and Subaru BRZ will help reduce body roll even further.', sku: 'CUS-HSB-807', url: 'https://i.imgur.com/CDbemPz.jpg', category: categories[7], price: 340.32},
    {name: 'ISC 5X100 TO 5X114 WHEEL ADAPTER (15MM / 25MM)', brand: 'ISC', description:'Finally, A name brand Subaru wheel adapter that works well and is affordable! No sense in paying 450.00 for competitors adapters any longer. This set (4) of bolt pattern adapters will allow you to bolt STI fitment wheels (5x114) to your WRX (Legacy, Forester, BRZ or any 5x100 Subaru)!', sku: 'ISC-WAD-908', url: 'https://i.imgur.com/jXLt6Y5.jpg', category: categories[8], price: 221.98},
    {name: 'WORK EMOTION CR 2P', brand: 'WORK', description:"These Work Emotion CR 2P wheels are featured in Bronze, Black, White, Silver and are sure to make your ride stand out! The design of these wheels will be the perfect complement to your build. The Work Emotion CR 2P is a Two Piece Forged wheel that will give your vehicle the look and performance you've been searching for. These stunning 5 spoke wheels will definitely transform your ride into something truly special!", sku: 'WRK-CR2-807', url: 'https://i.imgur.com/EPVdcwy.jpg', category: categories[8], price: 2600.99},
    {name: 'WORK VS XX', brand: 'WORK', description:'Work wheels are featured in Bronze, Black, White, Silver and are sure to make your ride stand out! The design of these wheels will be the perfect complement to your build.', sku: 'WRK-VSX-908', url: 'https://i.imgur.com/PZ9PBmv.jpg', category: categories[8], price: 2100.99},
    {name: 'GMR GS', brand: 'GMR', description:'wheels are featured in Bronze, Black, White, Silver and are sure to make your ride stand out!', sku: 'GMR-GSS-908', url: 'https://i.imgur.com/QvNG9kb.png', category: categories[8], price: 4700.00},
    {name: 'OPTION LAB R716', brand: 'OPTION LAB', description:'wheels are featured in Bronze, Black, White, Silver and are sure to make your ride stand out!', sku: 'OPL-R71-908', url: 'https://i.imgur.com/zwB29El.jpg', category: categories[8], price: 2300.00},
    {name: 'GRAM LIGHTS 57DR', brand: 'GRAM LIGHTS', description:'wheels are featured in Bronze, Black, White, Silver and are sure to make your ride stand out!', sku: 'GRL-57D-908', url: 'https://i.imgur.com/uECwzPC.jpg', category: categories[8], price: 1500.00},
    {name: 'ESR SR08', brand: 'ESR', description:'wheels are featured in Bronze, Black, White, Silver and are sure to make your ride stand out!', sku: 'ESR-SRO-908', url: 'https://i.imgur.com/z1PmxHQ.png', category: categories[8], price: 1290.00},
    {name: 'Work Wheels Wheel Emotion XD9', brand: 'WORK WHEELS', description:'The Emotion XD9 wheels are one of the more popular wheels. Made from low pressure cast aluminum, each one piece wheel feature an aggressive 9-spoke design with a large rim lip.', sku: 'WRK-XD9-908', url: 'https://i.imgur.com/Ich8dDS.jpg', category: categories[8], price: 1899.99},  
    {name: 'AMBIT RE02', brand: 'AMBIT', description:"One of our hottest sellers, the 15 spoke symmetrical RE02, is coming back and better than ever now available with a hub-centric fit. You will no longer need to run these wheels with spacers. The perfect fit is built in. Better yet, the RE02 is one of the few hub-centric fit wheels available for the Subaru market. We've upgraded our finish to a more durable, long-lasting texturized finish to ensure the longevity of your wheels. Our RE02 embodies an iconic look and displays attention to detail through every spoke. Bring out the aggressiveness of any application with the Ambit RE02.", sku: 'AMB-RE2-908', url: 'https://i.imgur.com/Mrt0iy2.jpg', category: categories[8], price: 1200.99},  
    {name: 'WORK WHEELS WORK MEISTER S1 3P', brand: 'WORK WHEELS', description:'With a completely redesigned center disk, the brand new WORK Meister S1 3p brings a new generation of style while keeping the heritage of the Meister series.', sku: 'WRK-S13-908', url: 'https://i.imgur.com/9mjeFsC.jpg', category: categories[8], price: 2399.95},  
    {name: 'KANSEI TANDEM DEEP CONCAVE HYPER SILVER', brand: 'KANSEI', description:'AN HOMAGE TO GODZILLA. OUR 6 SPOKE CONCAVE BLENDS OLD & NEW WITH INCREASED FITMENT OPTIONS.', sku: 'KNS-TND-908', url: 'https://i.imgur.com/HKZ3v8f.jpg', category: categories[8], price: 1399.95},  
    {name: 'Enkei Raijin 18x9.5 +45', brand: 'ENKEI', description:"The RAIJIN is a light weight street wheel designed for the everyday driver but with added MAT technology performance benefits. Named after the Japanese god of thunder, the Raijin is bound to help you bolt through traffic not only with style but with better overall performance.", sku: 'ENK-RJI-908', url: 'https://i.imgur.com/TXlewuD.jpg', category: categories[8], price: 2399.99},  
    {name: 'ENKEI RS05RR', brand: 'ENKEI', description:'Designed to look incredible while retaining Enkei’s racing spirit & functionality. The light weight RS05RR is made using Enkei’s MAT-DURA flow forming method.', sku: 'ENK-RS5-908', url: 'https://i.imgur.com/1RQuKx9.jpg', category: categories[8], price: 2499.94},  
    {name: 'VOLK RACING CE28 ClUB RACE II BACK EDITION ', brand: 'RAYS WHEELS', description:"Volkracing's lightest model CE28N is the base for the Club Racer wheel. High strength is built within to cater to the trade-off of the latest high performance compact sport cars with higher grip tires. Center hole design as been refined with the updated spoke profiles and center attachment. A driver can now comment to push the pedal while reducing traction loss at mid-speeds.CE28 Club Racer 2 Black Edition is an overseas exclusive model.", sku: 'VLK-CE2-908', url: 'https://i.imgur.com/bEFYgta.jpg', category: categories[8], price: 3450.94},  


]);
  
  console.log(items)
  
  process.exit();
  
})();




// {name: '', brand: '', description:'', sku: '', url: '', category: '', price: },